#!/bin/bash

if { [[ $1 == "" ]] || [[ $1 != "cheetah" && $1 != "panther" && $1 != "pantah" && $1 != "bluejay" ]]; }; then
	echo "Fuck!"
	exit 2
fi

orig=$1
tg=$1

# rename target to common target
if [[ $tg == "cheetah" || $tg == "panther" ]]; then
	tg="pantah"
fi

# build kernel
cd kernel
BUILD_AOSP_KERNEL=1 ./build_$tg.sh --kernel_package=@//aosp --lto=thin "${@:2}"
cd .. # god damn it gh

dst=~/kernel/out/${tg}/dist
chmod -x $dst/*

# deflate kernel headers
tar zxvf $dst/kernel-headers.tar.gz -C $dst
# , and copy original kernel headers
wget "https://android.googlesource.com/device/google/${tg}-kernels/6.1/+archive/refs/heads/main/25Q1-12919773/original-kernel-headers.tar.gz" -O /tmp/original-kernel-headers.tar.gz
tar zxvf /tmp/original-kernel-headers.tar.gz -C $dst/kernel-headers

# cleanup
for files in "*.tar.gz" "dtb.img" "*.dtbo" "Image" "Image.gz" "kernel_aarch64_modules" "kernel_kmi_symbol_list_violations_checked" "kernel_modules" "system_dlkm.img" "vendor_dlkm.img" "vendor_kernel_boot.img" "vmlinux*"; do
	rm $dst/$files
done

exit 0
