name: triggered kernel build
on:
    schedule:
      - cron: '0 0 * * 1'
    workflow_dispatch:
jobs:
    bluejay_gki:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] vy"
                git config --global user.email "vy@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-bluejay-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
            
            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp
  
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript bluejay

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: bluejay_gki
                 path: |
                    ~/kernel/out/bluejay/dist/*

            - name: upload to branch
              run: |
                git checkout prebuilt_bluejay_gki
                rm -rf *
                cp -rf ~/kernel/out/bluejay/dist/* .
                git add -A
                git commit -m '[kernel buildbot] tvy: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_bluejay_gki

    bluejay_gki-ksunext:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] vy"
                git config --global user.email "vy@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-bluejay-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp
            
            - name: clone wild kernel patches + susfs4ksu
              run: |
                git clone https://github.com/WildPlusKernel/kernel_patches.git
                git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
                mv kernel_patches ~/kernel
                mv susfs4ksu ~/kernel

            - name: patch kernel ksunext susfs
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next
                rm android/abi_gki_protected_exports_*
                cd ~/kernel
                cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./aosp/
                cp susfs4ksu/kernel_patches/fs/* ./aosp/fs/
                cp susfs4ksu/kernel_patches/include/linux/* ./aosp/include/linux/
                cp kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./aosp/KernelSU-Next
                cd ~/kernel/aosp/KernelSU-Next
                patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
                cd ..
                patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
                cd ~/kernel/aosp
                cp ../kernel_patches/next/syscall_hooks.patch ./
                cp ../kernel_patches/69_hide_stuff.patch ./
                patch -p1 -F 3 < syscall_hooks.patch
                patch -p1 -F 3 < 69_hide_stuff.patch
                cd ~/kernel
                echo "Adding configuration settings to gki_defconfig..."
                # Add KSU configuration settings
                echo "CONFIG_KSU=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_WITH_KPROBES=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                # Add SUSFS configuration settings
                echo "CONFIG_KSU_SUSFS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                # Add additional tmpfs config setting
                echo "CONFIG_TMPFS_XATTR=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                # Add additional config setting
                echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./aosp/arch/arm64/configs/gki_defconfig 
                echo "CONFIG_TCP_CONG_BBR=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_NET_SCH_FQ=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_BIC=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_HTCP=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                sed -i 's/check_defconfig//' ./aosp/build.config.gki
                cd ~/kernel
                sed -i '$s|echo "\$res"|echo "\$res-tvyiutnhisokewt"|' ./aosp/scripts/setlocalversion
                perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./aosp/scripts/mkcompile_h
                sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
                sed -E -i '/^CONFIG_LOCALVERSION=/ s/(.*)"$/\1-tvyiutnhisokewt"/' ./aosp/arch/arm64/configs/gki_defconfig

            - name: build gki with kernelsu-next
              run: |
                cd ~
                BUILD_TYPE=gki-ksunext ./kernel/buildscript bluejay

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: bluejay_gki-ksunext
                 path: |
                    ~/kernel/out/bluejay/dist/*

            - name: upload to branch
              run: |
                git checkout prebuilt_bluejay_gki-ksunext
                rm -rf *
                cp -rf ~/kernel/out/bluejay/dist/* .
                git add -A
                git commit -m '[kernel buildbot] tvy: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_bluejay_gki-ksunext
    
    pantah_gki:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] nhi"
                git config --global user.email "nhi@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp
  
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript pantah

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: pantah_gki
                 path: |
                    ~/kernel/out/pantah/dist/*
              
            - name: upload to branch
              run: |
                git checkout prebuilt_pantah_gki
                rm -rf *
                cp -rf ~/kernel/out/pantah/dist/* .
                git add -A
                git commit -m '[kernel buildbot] tnhi: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_pantah_gki
          
    pantah_gki-ksunext:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] nhi"
                git config --global user.email "nhi@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp

            - name: clone wild kernel patches + susfs4ksu
              run: |
                git clone https://github.com/WildPlusKernel/kernel_patches.git
                git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
                mv kernel_patches ~/kernel
                mv susfs4ksu ~/kernel

            - name: patch kernel ksunext susfs
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next
                rm android/abi_gki_protected_exports_*
                cd ~/kernel
                cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./aosp/
                cp susfs4ksu/kernel_patches/fs/* ./aosp/fs/
                cp susfs4ksu/kernel_patches/include/linux/* ./aosp/include/linux/
                cp kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./aosp/KernelSU-Next
                cd ~/kernel/aosp/KernelSU-Next
                patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
                cd ..
                patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
                cd ~/kernel/aosp
                cp ../kernel_patches/next/syscall_hooks.patch ./
                cp ../kernel_patches/69_hide_stuff.patch ./
                patch -p1 -F 3 < syscall_hooks.patch
                patch -p1 -F 3 < 69_hide_stuff.patch
                cd ~/kernel
                echo "Adding configuration settings to gki_defconfig..."
                # Add KSU configuration settings
                echo "CONFIG_KSU=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_WITH_KPROBES=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                # Add SUSFS configuration settings
                echo "CONFIG_KSU_SUSFS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                # Add additional tmpfs config setting
                echo "CONFIG_TMPFS_XATTR=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                # Add additional config setting
                echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./aosp/arch/arm64/configs/gki_defconfig 
                echo "CONFIG_TCP_CONG_BBR=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_NET_SCH_FQ=y" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_BIC=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                echo "CONFIG_TCP_CONG_HTCP=n" >> ./aosp/arch/arm64/configs/gki_defconfig
                sed -i 's/check_defconfig//' ./aosp/build.config.gki
                cd ~/kernel
                sed -i '$s|echo "\$res"|echo "\$res-tvyiutnhisokewt"|' ./aosp/scripts/setlocalversion
                perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./aosp/scripts/mkcompile_h
                sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
                sed -E -i '/^CONFIG_LOCALVERSION=/ s/(.*)"$/\1-tvyiutnhisokewt"/' ./aosp/arch/arm64/configs/gki_defconfig
                
            - name: build gki with kernelsu-next
              run: |
                cd ~
                BUILD_TYPE=gki-ksunext ./kernel/buildscript pantah

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: pantah_gki-ksunext
                 path: |
                    ~/kernel/out/pantah/dist/*

            - name: upload to branch
              run: |
                git checkout prebuilt_pantah_gki-ksunext
                rm -rf *
                cp -rf ~/kernel/out/pantah/dist/* .
                git add -A
                git commit -m '[kernel buildbot] tnhi: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_pantah_gki-ksunext
