name: triggered kernel build
on:
    push:
        branches:
            - sauce
    workflow_dispatch:
jobs:
    bluejay_gki:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "Kernel Buildbot"
                git config --global user.email "gh@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-bluejay-6.1-android16 --depth 1
            
            - name: hax because google gay
              run: |
                cd ~/kernel
                sed -i 's,android-gs-bluejay-6.1-android16,refs/tags/android-16.0.0_r0.10,g' .repo/manifests/default.xml
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
  
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript bluejay

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: bluejay_gki
                 path: |
                    ~/kernel/out/bluejay/dist/*

            - name: upload to branch
              run: |
                git checkout prebuilt_bluejay_gki
                rm -rf *
                cp -rf ~/kernel/out/bluejay/dist/* .
                git add -A
                git commit -m 'Upload prebuilt to branch' --signoff
                git push -u origin prebuilt_bluejay_gki

    pantah_gki:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "Kernel Buildbot"
                git config --global user.email "gh@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android16 --depth 1
            
            - name: hax because google gay
              run: |
                cd ~/kernel
                sed -i 's,android-gs-pantah-6.1-android16,refs/tags/android-16.0.0_r0.10,g' .repo/manifests/default.xml
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript pantah

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: pantah_gki
                 path: |
                    ~/kernel/out/pantah/dist/*
              
            - name: upload to branch
              run: |
                git checkout prebuilt_pantah_gki
                rm -rf *
                cp -rf ~/kernel/out/pantah/dist/* .
                git add -A
                git commit -m '[kernel buildbot] tnhi: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_pantah_gki
